-- 코드를 입력하세요
# SELECT B.CATEGORY, SALES AS TOTAL_SALES
# FROM BOOK AS B
# JOIN (SELECT BOOK_ID, SUM(SALES) AS SALES
#      FROM BOOK_SALES
#      WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
#      GROUP BY BOOK_ID) AS TMP
# ON B.BOOK_ID = TMP.BOOK_ID
# GROUP BY B.CATEGORY
# ORDER BY B.CATEGORY ASC


# SELECT BOOK_ID, SUM(SALES) AS SUM_SALES
# FROM BOOK_SALES
# WHERE YEAR(SALES_DATE)='2022' AND MONTH(SALES_DATE) = '1'
# GROUP BY BOOK_ID


SELECT B.CATEGORY, SUM(TMP.SUM_SALES) AS TOTAL_SALES
FROM BOOK AS B
JOIN (SELECT BOOK_ID, SUM(SALES) AS SUM_SALES
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE)='2022' AND MONTH(SALES_DATE) = '1'
    GROUP BY BOOK_ID) AS TMP
ON B.BOOK_ID = TMP.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY
