-- 생산일자가 2022년 5월인 식품 확인
# SELECT DATE_FORMAT(PRODUCE_DATE, '%Y-%m-%d') AS PRODUCE_DATE, // 날짜 확인완료 
# SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMT
# FROM FOOD_ORDER
# WHERE PRODUCE_DATE >= '2022-05-01'
# AND PRODUCE_DATE < '2022-06-01'
# GROUP BY PRODUCT_ID;

-- 생산일자 5월인 식품들의 ID, 이름, 총매출 조회하기 (총매출 기준 내림차순, 식품ID 오름차순)
SELECT PRD.PRODUCT_ID, PRD.PRODUCT_NAME, PRD.PRICE * ORD.TOTAL_AMT AS TOTAL_SALES
FROM FOOD_PRODUCT AS PRD
JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE >= '2022-05-01'
    AND PRODUCE_DATE < '2022-06-01'
    GROUP BY PRODUCT_ID) AS ORD
ON PRD.PRODUCT_ID = ORD.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRD.PRODUCT_ID ASC;

