-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, (P.PRICE * TMP.SALES_AMOUNT) AS SALES
FROM PRODUCT AS P
JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID) AS TMP
ON P.PRODUCT_ID = TMP.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC , P.PRODUCT_CODE ASC

