-- 아이템의 희귀도가 'RARE'인 아이템들의 모든 다음 업그레이드 아이템의 아이템 ID(ITEM_ID), 아이템 명(ITEM_NAME), 아이템의 희귀도(RARITY)를 출력하는 SQL 문을 작성해 주세요. 이때 결과는 아이템 ID를 기준으로 내림차순 정렬주세요.


-- 아이템의 희귀도가 RARE인 아이템 추출
# SELECT ITEM_ID
# FROM ITEM_INFO
# WHERE RARITY = 'RARE';

-- 희귀도가 RARE인 아이템의 다음 업그레이드 아이템 추출 (ITEM_TREE의 PARENT_ITEM_ID가 위에서 추출한 ITEM_ID와 일치해야함)
# SELECT TREE.ITEM_ID
# FROM ITEM_TREE AS TREE
# JOIN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE') AS RTEM
# ON TREE.PARENT_ITEM_ID = RTEM.ITEM_ID

-- 희귀도 RARE의 다음 업글 아이템의 정보 확인하기
SELECT INF.ITEM_ID, INF.ITEM_NAME, INF.RARITY 
FROM ITEM_INFO AS INF
JOIN (SELECT TREE.ITEM_ID
    FROM ITEM_TREE AS TREE
    JOIN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE') AS RTEM
    ON TREE.PARENT_ITEM_ID = RTEM.ITEM_ID) AS UPG
ON INF.ITEM_ID = UPG.ITEM_ID
ORDER BY INF.ITEM_ID DESC;


