-- 코드를 입력하세요
# SELECT PRODUCT_NAME,CATEGORY,MAX(PRICE)
# FROM FOOD_PRODUCT
# GROUP BY CATEGORY

-- 카테고리 별 MAX PRICE 확인하기
# SELECT CATEGORY, MAX(PRICE)
# FROM FOOD_PRODUCT
# GROUP BY CATEGORY;

-- 카테고리별 MAX PRICE 정보와 일치하는 정보만 가져오기
SELECT PRD.CATEGORY, PRD.PRICE, PRD.PRODUCT_NAME
FROM FOOD_PRODUCT AS PRD
JOIN (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY) AS MXP
ON PRD.CATEGORY = MXP.CATEGORY AND PRD.PRICE = MXP.MAX_PRICE
WHERE PRD.CATEGORY IN ('과자','국','김치','식용유')
ORDER BY PRD.PRICE DESC;