-- 코드를 입력하세요
# '서울'에 위치한 식당을 우선적으로 추출해야 하는데 해당 부분을 빼고 계속 생각함...

SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(AVG(RR.REVIEW_SCORE),2) AS SCORE
FROM (SELECT *
FROM REST_INFO
HAVING LEFT(ADDRESS, 2) = '서울') AS RI
JOIN REST_REVIEW AS RR
ON RI.REST_ID = RR.REST_ID
GROUP BY RR.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC

